[k8s]
config_mode = "local"  # Use "local" or "in-cluster"
namespace = "ps"
deployment_name = "ps-test"
app_name = "nginx"
perf_deployment_name = "ps-perf"
perf_app_name = " threading-metric-exporter-app"

[scaling]
timeout = 600  # Timeout in seconds for operations
interval = 10   # Interval in seconds to check status

[logging]
log_level = "INFO"  # Possible values: DEBUG, INFO, WARNING, ERROR, CRITICAL

[proxy]
http_proxy = ""
https_proxy = ""
verify_ssl = true  # Set to false to disable SSL verification

[parallelstore]
mount_path = "/data"
instance_name = "test-instance-persistent"
region = "us-central1-a"
project_id = "lab-gke-se"

[GCS]
bucket_name= "import-export-1234"