apiVersion: apps/v1
kind: Deployment
metadata:
  name: ps-test
  namespace: ps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: import-export
      containers:
        - name: nodemount-testing
          image: nginx  
          ports:
            - containerPort: 7001
          volumeMounts:
            - name: persistent-pvc
              mountPath: /data
              readOnly: false
      volumes:
        - name: persistent-pvc
          persistentVolumeClaim:
            claimName: persistent-pvc