apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 27000Gi
  storageClassName: ""
  volumeName: persistent-pv