apiVersion: v1
kind: Pod
metadata:
  name: nodemount-test-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: parallelstore-volume
          mountPath: /data
  volumes:
    - name: parallelstore-volume
      persistentVolumeClaim:
        claimName: persistent-pvc