apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: {{ .Values.deployment.serviceAccountName }}
      containers:
        - name: {{ .Values.deployment.container.name }}
          image: {{ .Values.deployment.container.image }}
          ports:
            - containerPort: {{ .Values.deployment.container.port }}
          volumeMounts:
            - name: {{ .Values.pvc.name }}
              mountPath: {{ .Values.deployment.container.mountPath }}
              readOnly: {{ .Values.deployment.container.readOnly }}
      volumes:
        - name: {{ .Values.pvc.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}