apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: parallelstore.csi.storage.gke.io
    volumeHandle: {{ .Values.pv.volumeHandle | quote }}
    volumeAttributes:
      accessPoints: {{ .Values.pv.accessPoints | quote }}
      network: {{ .Values.pv.network }}
      mountLocality: node
  mountOptions:
    - disable-caching